version: '3'

services:

  registry-nginx-proxy:
    build: ./registry-nginx/.
    restart: always
    container_name: registry-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - registry-nginx-conf:/etc/nginx/conf.d
      - registry-nginx-vhost:/etc/nginx/vhost.d
      - registry-nginx-html:/usr/share/nginx/html
      - registry-nginx-ssl:/etc/nginx/certs:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  registry-nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: registry-nginx-gen
    restart: always
    command: -notify-sighup registry-nginx-proxy -wait 5s:30s -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - registry-nginx-conf:/etc/nginx/conf.d
      - registry-nginx-vhost:/etc/nginx/vhost.d
      - registry-nginx-html:/usr/share/nginx/html
      - registry-nginx-gen-tmpl:/etc/docker-gen/templates
      - registry-nginx-ssl:/etc/nginx/certs:ro
    links:
      - registry-nginx-proxy

  registry-nginx-letsencrypt:
    build: ./docker-letsencrypt-nginx-proxy-companion/.
    container_name: registry-nginx-letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - registry-nginx-conf:/etc/nginx/conf.d
      - registry-nginx-vhost:/etc/nginx/vhost.d
      - registry-nginx-html:/usr/share/nginx/html
      - registry-nginx-gen-tmpl:/etc/docker-gen/templates
      - registry-nginx-ssl:/etc/nginx/certs:rw
    environment:
      NGINX_DOCKER_GEN_CONTAINER: registry-nginx-gen
      # ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
    links:
      - registry-nginx-proxy
      - registry-nginx-gen

  registry:
    image: registry:2
    restart: always
    volumes:
      - docker-registry-data:/var/lib/registry
    environment:
      VIRTUAL_HOST: yourdomain.example.com
      LETSENCRYPT_HOST: yourdomain.example.com
      LETSENCRYPT_EMAIL: youremail@yourdomain.example.com


volumes:

  docker-registry-data:
    external: true

  registry-nginx-conf:
  registry-nginx-vhost:
  registry-nginx-html:
  registry-nginx-gen-tmpl:
  registry-nginx-ssl:
